apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: osspa-org
  namespace: osspa
spec:
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  dnsNames:
    - dev.osspa.org
  issuerRef:
    kind: Issuer
    name: azure-dns-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: osspa-org-tls
  secretTemplate:
    annotations:
      my-secret-annotation-1: osspa-org
    labels:
      my-secret-label: osspa-org