kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipelinepvc
  namespace: osspa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium
  volumeMode: Filesystem
